code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension Gruntfuggly.todo-tree
code --install-extension kesmarag.adwaita-base16
code --install-extension lfs.vscode-emacs-friendly
code --install-extension ms-python.python
code --install-extension ms-vscode.Go
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension perragnaredin.september-steel
code --install-extension PeterJausovec.vscode-docker
code --install-extension PKief.material-icon-theme
code --install-extension rebornix.nova
code --install-extension shardulm94.trailing-spaces
code --install-extension sneezry.vscode-instant-weather
code --install-extension SolarLiner.linux-themes
code --install-extension wmaurer.vscode-jumpy
code --install-extension yzhang.markdown-all-in-one
code --install-extension zhuangtongfa.Material-theme
